core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('shop', views.ItemListView.as_view(), name='shop'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product-detail'),
    path('checkout/cart', views.OrderSummaryView.as_view(), name='checkout-cart'),
    path('remove-from-cart/<slug>', views.remove_from_cart, name='remove-from-cart'),
    path('quantity-minus-from-cart',
         views.quantity_minus_from_cart, name='quantity-minus-from-cart'),
    path('quantity-plus-from-cart',
         views.quantity_plus_from_cart, name='quantity-plus-from-cart'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify

CATEGORY_CHOICES = (
    ('V', 'Vegetables'),
    ('F', 'Fruits'),
    ('J', 'Juice'),
    ('D', 'Dried')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount = models.IntegerField("Discount (%)", blank=True, null=True)
    discount_price = models.FloatField("Price after discount", blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=1)
    slug = models.SlugField(unique=True, editable=False)
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }
        return reverse("core:product-detail", kwargs=kwargs)

    def get_add_to_cart_url(self):
        kwargs = {
            'slug': self.slug
        }
        return reverse("core:add-to-cart", kwargs=kwargs)

    def get_remove_from_cart_url(self):
        kwargs = {
            'slug': self.slug
        }
        return reverse("core:remove-from-cart", kwargs=kwargs)

    def save(self, *args, **kwargs):
        if self.discount:
            self.discount_price = self.price * (1 - self.discount / 100)
        if not self.slug:
            self.slug = slugify(self.title)
        super(Item, self).save(*args, **kwargs)


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             blank=True, null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return "{} or {}".format(self.quantity, self.item.title)

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        if self.item.discount_price:
            return self.quantity * self.item.discount_price
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_sub_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total

    def get_total(self):
        total_discount = 0
        for order_item in self.items.all():
            total_discount += order_item.get_total_discount_item_price()
        return total_discount

    def get_total_amount_saved(self):
        return self.get_sub_total() - self.get_total()

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.webp' %});">
	<div class="container">
		<div class="row no-gutters slider-text align-items-center justify-content-center">
			<div class="col-md-9 ftco-animate text-center">
				<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'core:home' %}">Home</a></span> <span>Cart</span></p>
				<h1 class="mb-0 bread">My Cart</h1>
			</div>
		</div>
	</div>
</div>

<section class="ftco-section ftco-cart">
	<div class="container">
		<div class="row">
			<div class="col-md-12 ftco-animate">
				<div class="cart-list">
					<table class="table">
						<thead class="thead-primary">
							<tr class="text-center">
								<th>&nbsp;</th>
								<th>&nbsp;</th>
								<th>Product name</th>
								<th>Price</th>
								<th>Quantity</th>
								<th>Total</th>
							</tr>
						</thead>
						<tbody>
						{% if order_list %}
							{% for order in order_list.items.all %}
							<tr class="text-center" id="order-item{{ forloop.counter0 }}">
								<td class="product-remove">
									<a href="{% url 'core:remove-from-cart' order.item.slug %}"><span class="ion-md-close"></span></a>
								</td>

								<td class="image-prod">
									<div class="img" style="background-image:url({% static 'images/product-1.webp' %});"></div>
								</td>

								<td class="product-name">
									<h3>{{ order.item.title }}</h3>
									<p>Far far away, behind the word mountains, far from the countries</p>
								</td>

								<td class="price">
									{% if order.item.discount %}
										<span class="cart-products__real-prices">${{ order.item.discount_price|floatformat:2 }}</span>
										<p class="cart-products__discount-prices">
											<del>${{ order.item.price|floatformat:2 }}</del>
											<span class="cart-products__percent-prices">-{{ order.item.discount }}%</span>
										</p>
									{% else %}
										<span class="cart-products__real-prices">${{ order.item.price|floatformat:2 }}</span>
									{% endif %}
								</td>

								<td class="quantity">
									<div class="input-group mb-3">
										<span class="input-group-btn">
											<button type="button" class="quantity-left-minus btn" data-type="minus" onclick="quantityMinusPlus(this)" slug="{{ order.item.slug }}" csrf-token="{{ csrf_token }}" data-field="{{ forloop.counter0 }}">
												<i class="ion-ios-remove"></i>
											</button>
										</span>
										<input type="text" name="quantity" id="quantity{{ forloop.counter0 }}" class="quantity form-control input-number" value="{{ order.quantity }}" min="1" max="100" />
										<span class="input-group-btn">
											<button type="button" class="quantity-right-plus btn" data-type="plus" onclick="quantityMinusPlus(this)" slug="{{ order.item.slug }}" csrf-token="{{ csrf_token }}" data-field="{{ forloop.counter0 }}">
												<i class="ion-ios-add"></i>
											</button>
										</span>
									</div>
								</td>
								<td class="total" id="total-item-price{{ forloop.counter0 }}" style="font-weight: 500; font-size: 17px;">
								{% if order.item.discount %}
									${{ order.get_total_discount_item_price|floatformat:2 }}
								{% else %}
									${{ order.get_total_item_price|floatformat:2 }}
								{% endif %}
								</td>
							</tr>
							{% endfor %}
						{% else %}
							<tr>
								<td class="product-name" colspan="6" style="text-align: left !important;">Your cart is empty...</th>
							</tr>
						{% endif %}
						<!-- END TR-->
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="row justify-content-end">
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Coupon Code</h3>
					<p>Enter your coupon code if you have one</p>
					<form action="#" class="info">
						<div class="form-group">
							<label for="">Coupon code</label>
							<input type="text" class="form-control text-left px-3" placeholder="">
						</div>
					</form>
				</div>
				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Apply Coupon</a></p>
			</div>
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Estimate shipping and tax</h3>
					<p>Enter your destination to get a shipping estimate</p>
					<form action="#" class="info">
						<div class="form-group">
							<label for="">Country</label>
							<input type="text" class="form-control text-left px-3" placeholder="">
						</div>
						<div class="form-group">
							<label for="country">State/Province</label>
							<input type="text" class="form-control text-left px-3" placeholder="">
						</div>
						<div class="form-group">
							<label for="country">Zip/Postal Code</label>
							<input type="text" class="form-control text-left px-3" placeholder="">
						</div>
					</form>
				</div>
				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Estimate</a></p>
			</div>
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Cart Totals</h3>
					<p class="d-flex">
						<span>Subtotal</span>
						<span id="sub-total">${{ order_list.get_sub_total|floatformat:2 }}</span>
					</p>
					<p class="d-flex">
						<span>Delivery</span>
						<span>$0.00</span>
					</p>
					<p class="d-flex">
						<span>Discount</span>
						<span id="total-amount-saved">${{ order_list.get_total_amount_saved|floatformat:2 }}</span>
					</p>
					<hr>
					<p class="d-flex total-price">
						<span>Total</span>
						<span id="total">${{ order_list.get_total|floatformat:2 }}</span>
					</p>
				</div>
				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
			</div>
		</div>
	</div>
</section>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/quantity-minus-plus.js' %}"></script>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="hero-wrap hero-bread" style="background-image: url({% static 'images/bg_1.webp' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="{% url 'core:home' %}">Home</a></span> <span>Contact us</span></p>
            <h1 class="mb-0 bread">Contact us</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section contact-section bg-light">
      <div class="container">
      	<div class="row d-flex mb-5 contact-info">
          <div class="w-100"></div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Phone:</span> <a href="tel://0123456789">+ 0123 4567 89</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="info bg-white p-4">
	            <p><span>Website</span> <a href="#">yoursite.com</a></p>
	          </div>
          </div>
        </div>
        <div class="row block-9">
          <div class="col-md-6 order-md-last d-flex">
            <form action="#" class="bg-white p-5 contact-form">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Your Email">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Subject">
              </div>
              <div class="form-group">
                <textarea name="" id="" cols="30" rows="7" class="form-control" placeholder="Message"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
              </div>
            </form>
          
          </div>

          <div class="col-md-6 d-flex">
          	<div id="map" class="bg-white"></div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section id="home-section" class="hero">
	<div class="home-slider owl-carousel">
		<div class="slider-item" style="background-image: url({% static 'images/bg_1.webp' %});">
			<div class="overlay"></div>
			<div class="container">
				<div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

					<div class="col-md-12 ftco-animate text-center">
						<h1 class="mb-2">We serve Fresh Vegestables &amp; Fruits</h1>
						<h2 class="subheading mb-4">We deliver organic vegetables &amp; fruits</h2>
						<p><a href="#" class="btn btn-primary">View Details</a></p>
					</div>

				</div>
			</div>
		</div>

		<div class="slider-item" style="background-image: url({% static 'images/bg_2.webp' %});">
			<div class="overlay"></div>
			<div class="container">
				<div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

					<div class="col-sm-12 ftco-animate text-center">
						<h1 class="mb-2">100% Fresh &amp; Organic Foods</h1>
						<h2 class="subheading mb-4">We deliver organic vegetables &amp; fruits</h2>
						<p><a href="#" class="btn btn-primary">View Details</a></p>
					</div>

				</div>
			</div>
		</div>
	</div>
</section>

<section class="ftco-section">
	<div class="container">
		<div class="row no-gutters ftco-services">
			<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
				<div class="media block-6 services mb-md-0 mb-4">
					<div class="icon bg-color-1 active d-flex justify-content-center align-items-center mb-2">
						<span class="flaticon-shipped"></span>
					</div>
					<div class="media-body">
						<h3 class="heading">Free Shipping</h3>
						<span>On order over $100</span>
					</div>
				</div>      
			</div>
			<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
				<div class="media block-6 services mb-md-0 mb-4">
					<div class="icon bg-color-2 d-flex justify-content-center align-items-center mb-2">
						<span class="flaticon-diet"></span>
					</div>
					<div class="media-body">
						<h3 class="heading">Always Fresh</h3>
						<span>Product well package</span>
					</div>
				</div>    
			</div>
			<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
				<div class="media block-6 services mb-md-0 mb-4">
					<div class="icon bg-color-3 d-flex justify-content-center align-items-center mb-2">
						<span class="flaticon-award"></span>
					</div>
					<div class="media-body">
						<h3 class="heading">Superior Quality</h3>
						<span>Quality Products</span>
					</div>
				</div>      
			</div>
			<div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
				<div class="media block-6 services mb-md-0 mb-4">
					<div class="icon bg-color-4 d-flex justify-content-center align-items-center mb-2">
						<span class="flaticon-customer-service"></span>
					</div>
					<div class="media-body">
						<h3 class="heading">Support</h3>
						<span>24/7 Support</span>
					</div>
				</div>      
			</div>
		</div>
	</div>
</section>

<section class="ftco-section ftco-category ftco-no-pt">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-6 order-md-last align-items-stretch d-flex">
						<div class="category-wrap-2 ftco-animate img align-self-stretch d-flex" style="background-image: url({% static 'images/category.webp' %});">
							<div class="text text-center">
								<h2>Vegetables</h2>
								<p>Protect the health of every home</p>
								<p><a href="{% url 'core:shop' %}" class="btn btn-primary">Shop now</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="category-wrap ftco-animate img mb-4 d-flex align-items-end" style="background-image: url({% static 'images/category-1.webp' %});">
							<div class="text px-3 py-1">
								<h2 class="mb-0"><a href="#">Fruits</a></h2>
							</div>
						</div>
						<div class="category-wrap ftco-animate img d-flex align-items-end" style="background-image: url({% static 'images/category-2.webp' %});">
							<div class="text px-3 py-1">
								<h2 class="mb-0"><a href="#">Vegetables</a></h2>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-4">
				<div class="category-wrap ftco-animate img mb-4 d-flex align-items-end" style="background-image: url({% static 'images/category-3.webp' %});">
					<div class="text px-3 py-1">
						<h2 class="mb-0"><a href="#">Juices</a></h2>
					</div>		
				</div>
				<div class="category-wrap ftco-animate img d-flex align-items-end" style="background-image: url({% static 'images/category-4.webp' %});">
					<div class="text px-3 py-1">
						<h2 class="mb-0"><a href="#">Dried</a></h2>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="ftco-section">
	<div class="container">
		<div class="row justify-content-center mb-3 pb-3">
			<div class="col-md-12 heading-section text-center ftco-animate">
				<span class="subheading">Featured Products</span>
				<h2 class="mb-4">Our Products</h2>
				<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
			</div>
		</div>   		
	</div>
	<div class="container">
		<div class="row">
		{% for item in object_list %}
			<div class="col-md-6 col-lg-3 ftco-animate">
				<div class="product">
					<a href="{{ item.get_absolute_url }}" class="img-prod"><img class="img-fluid" src="{% static 'images/product-1.webp' %}" alt="">
						{% if item.discount %} <span class="status">{{ item.discount }}%</span> {% endif %}
						<div class="overlay"></div>
					</a>
					<div class="text py-3 pb-4 px-3 text-center">
						<h3><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></h3>
						<div class="d-flex">
							<div class="pricing">
								<p class="price">
									{% if item.discount %}
									<span class="mr-2 price-dc">${{ item.price|floatformat:2 }}</span>
									<span class="price-sale">${{ item.discount_price|floatformat:2 }}</span>
									{% else %}
									<span class="price">${{ item.price|floatformat:2 }}</span>
									{% endif %}
								</p>
							</div>
						</div>
						<div class="bottom-area d-flex px-3">
							<div class="m-auto d-flex">
								<button class="add-to-cart d-flex justify-content-center align-items-center text-center">
									<span><i class="ion-ios-menu"></i></span>
								</button>
								<button class="buy-now d-flex justify-content-center align-items-center mx-1" onclick="quantityMinusPlus(this)" id="" data-type="plus", slug="{{ item.slug }}" csrf-token={{csrf_token}} data_field="">
									<span><i class="ion-ios-cart"></i></span>
								</button>
								<button class="heart d-flex justify-content-center align-items-center ">
									<span><i class="ion-ios-heart"></i></span>
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
		</div>
	</div>
</section>
	
<section class="ftco-section img" style="background-image: url({% static 'images/bg_3.webp' %});">
	<div class="container">
		<div class="row justify-content-end">
			<div class="col-md-6 heading-section ftco-animate deal-of-the-day ftco-animate">
				<span class="subheading">Best Price For You</span>
				<h2 class="mb-4">Deal of the day</h2>
				<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
				<h3><a href="#">Spinach</a></h3>
				<span class="price">$10 <a href="#">now $5 only</a></span>
				<div id="timer" class="d-flex mt-5">
					<div class="time" id="days"></div>
					<div class="time pl-3" id="hours"></div>
					<div class="time pl-3" id="minutes"></div>
					<div class="time pl-3" id="seconds"></div>
				</div>
			</div>
		</div>   		
	</div>
</section>

<section class="ftco-section testimony-section">
	<div class="container">
		<div class="row justify-content-center mb-5 pb-3">
			<div class="col-md-7 heading-section ftco-animate text-center">
				<span class="subheading">Testimony</span>
				<h2 class="mb-4">Our satisfied customer says</h2>
				<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
			</div>
		</div>
		<div class="row ftco-animate">
			<div class="col-md-12">
				<div class="carousel-testimony owl-carousel">
					<div class="item">
						<div class="testimony-wrap p-4 pb-5">
							<div class="user-img mb-5" style="background-image: url({% static 'images/person_1.webp' %})">
								<span class="quote d-flex align-items-center justify-content-center">
								<i class="icon-quote-left"></i>
								</span>
							</div>
							<div class="text text-center">
								<p class="mb-5 pl-4 line">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<p class="name">Garreth Smith</p>
								<span class="position">Marketing Manager</span>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="testimony-wrap p-4 pb-5">
							<div class="user-img mb-5" style="background-image: url({% static 'images/person_2.webp' %})">
								<span class="quote d-flex align-items-center justify-content-center">
								<i class="icon-quote-left"></i>
								</span>
							</div>
							<div class="text text-center">
								<p class="mb-5 pl-4 line">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<p class="name">Garreth Smith</p>
								<span class="position">Interface Designer</span>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="testimony-wrap p-4 pb-5">
							<div class="user-img mb-5" style="background-image: url({% static 'images/person_3.webp' %})">
								<span class="quote d-flex align-items-center justify-content-center">
								<i class="icon-quote-left"></i>
								</span>
							</div>
							<div class="text text-center">
								<p class="mb-5 pl-4 line">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<p class="name">Garreth Smith</p>
								<span class="position">UI Designer</span>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="testimony-wrap p-4 pb-5">
							<div class="user-img mb-5" style="background-image: url({% static 'images/person_1.webp' %})">
								<span class="quote d-flex align-items-center justify-content-center">
								<i class="icon-quote-left"></i>
								</span>
							</div>
							<div class="text text-center">
								<p class="mb-5 pl-4 line">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<p class="name">Garreth Smith</p>
								<span class="position">Web Developer</span>
							</div>
						</div>
					</div>
					<div class="item">
						<div class="testimony-wrap p-4 pb-5">
							<div class="user-img mb-5" style="background-image: url({% static 'images/person_1.webp' %})">
								<span class="quote d-flex align-items-center justify-content-center">
								<i class="icon-quote-left"></i>
								</span>
							</div>
							<div class="text text-center">
								<p class="mb-5 pl-4 line">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
								<p class="name">Garreth Smith</p>
								<span class="position">System Analyst</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}
{% block javascript %}
<script src="{% static 'js/quantity-minus-plus.js' %}"></script>
{% endblock %}

templates/navbar.html
{% load cart_template_tags %}

<div class="container">
    <a class="navbar-brand" href="{% url 'core:home' %}">The Green</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="{% url 'core:home' %}" class="nav-link">Home</a></li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
        <div class="dropdown-menu" aria-labelledby="dropdown04">
            <a class="dropdown-item" href="{% url 'core:shop' %}">Shop</a>
            <a class="dropdown-item" href="wishlist.html">Wishlist</a>
            <a class="dropdown-item" href="{% url 'core:checkout-cart' %}">Cart</a>
            <a class="dropdown-item" href="checkout.html">Checkout</a>
        </div>
        </li>
        <li class="nav-item"><a href="{% url 'core:about' %}" class="nav-link">About</a></li>
        <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>
        <li class="nav-item"><a href="{% url 'core:contact' %}" class="nav-link">Contact</a></li>
        {% if request.user.is_authenticated %}
            <li class="nav-item cta cta-colored"><a href="{% url 'core:checkout-cart' %}" class="nav-link" id="cart-item-count"><span class="icon-shopping_cart"></span>[{{ request.user|cart_item_count }}]</a></li>
            <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link">Logout</a></li>
        {% else %}
            <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link">Login</a></li>
        {% endif %}

        </ul>
    </div>
</div>